= Kubernetes - Enforcing Network Security Policies with Calico

== Introduction

https://www.projectcalico.org[Calico] is an open-source plugin that allows for fine-grained network policy enforcement, ensuring that traffic within your Kubernetes cluster can only flow in the direction that you specify.  As an example, if we take a scenario where Kubernetes namespaces are used opt enforce boundaries between products, or even enforce boundaries between different environments (e.g. development vs production), network policies can be configured to ensure no unauthorized network traffic is allowed beyond its boundary.  Think of it as being similar to applying Security Groups in the AWS world.

This exercise will walk you through configuring Calico and applying a Network Policy.

== Pre-requisites

Although Calico can be installed on a variety of Kubernetes configurations, this exercise assumes that you have a running Kubernetes cluster deployed to AWS via `kops`.

== Installation

Edit the existing kubernetes cluster config, where `${NAME}` is the name of your cluster, and `${KUBERNETES_STATE_STORE_BUCKET}` is the name of the S3 bucket originally created by kops as its state store:

----
kops edit cluster ${NAME} --state s3://${KUBERNETES_STATE_STORE_BUCKET}
----

Update the networking configuration to use `calico` by setting the following property:

----
  networking:
    calico: 
      crossSubnet: true
----

Finally, apply the changes to your cluster:

----
# View changes that will be applied
kops update cluster ${NAME} --state s3://${KUBERNETES_STATE_STORE_BUCKET}

# Apply the changes
kops update cluster ${NAME} --state s3://${KUBERNETES_STATE_STORE_BUCKET} --yes

# Determine if any of the nodes will require a restart
kops rolling-update cluster ${NAME} --state s3://${KUBERNETES_STATE_STORE_BUCKET}

# Restart the nodes (warning:  this may take 5-15 minutes depending on the size of your cluster)
kops rolling-update cluster ${NAME} --state s3://${KUBERNETES_STATE_STORE_BUCKET} --yes
----


== Configuration:  Enforcing Network Isolation

This exercise introduces you to configuring Calico.  We will create a namespace, deploy some test pods into it, and see the before and after effects of configuring a Calico based Network Policy.

Create a namespace:

----
kubectl create ns ns-1
----

Deploy a container into namespace `ns-1` that will expose an http endpoint, and log all requests it receives.

----
# Creates a Deployment, ReplicaSet and Pod
kubectl run --namespace=ns-1 http-echo --image=solsson/http-echo --env="PORT=80" --port=80

# Label the pod (we will use labels as part of defining network policies)
kubectl label po --selector=run=http-echo --namespace=ns-1 app=http-echo

# Creates a Service to expose the pod
kubectl expose --namespace=ns-1 deployment http-echo --port=80
----

Monitor the logs of the deployed container by querying the name of the pod defined with the label `run-http-echo`, then passing it to the `kubectl logs` command:

----
kubectl get po --selector=run=http-echo --namespace=ns-1 -o jsonpath='{.items[*].metadata.name}' | xargs kubectl logs -f --namespace=ns-1
----

In another shell, deploy a second container:

----
kubectl run --namespace=ns-1 -i --tty busybox --image=busybox --restart=Never -- sh
----

We will now attempt to call the `http-echo` pod from our `busybox` pod by performing an HTTP POST .  As we have no network policies in place, we should see the following command return successfully with a 200 response, along with a log message being output in the `http-echo` shell window:

----
busybox shell>  wget -S http://http-echo.ns-1.svc.cluster.local/test --post-data '{"message":"hello"}'
----

Let's now create a Network Policy, but we will not configure any rules which by default will deny all traffic within the namespace.  Leaving the 2 shells open from the previous steps, run the following in another shell:

----
kubectl create -f deny-all-by-default-network-policy.yaml --namespace=ns-1
----

When running the following command again in shell 2, we should see it eventually timeout and fail:

----
busybox shell>  wget -S http://http-echo.ns-1.svc.cluster.local/test --post-data '{"message":"hello"}'
----

We will now delete the NetworkPolicy that we just created, and create a new NetworkPolicy with a rule defined.  If you `cat `allow-network-policy.yaml` you will see the following rule defined:

----
spec:
  podSelector:
    matchLabels:
      app: http-echo
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: busybox
----

The rule above is stating that for every pod that has the label `app: http-echo` defined, allow access to it from pods that have the label `app: busybox` defined.

Run the following to remove the deny all by default rule, and replace with the above allow rule:

----
kubectl delete netpol deny-all-by-default --namespace=ns-1
kubectl create -f allow-network-policy.yaml --namespace=ns-1
----

If we repeat the following command in shell 2, the call should still timeout and fail:

----
busybox shell>  wget -S http://http-echo.ns-1.svc.cluster.local/test --post-data '{"message":"hello"}'
----

Why is this still failing even after creating a rule?  It is failing because we configured the rule so that only pods with the label `app: busybox` are authorized to call pods with the label `app: http-echo`.  Let's go ahead and label our `busybox` pod:

----
kubectl label po --selector=run=busybox --namespace=ns-1 app=busybox
----

Repeating the test in shell 2 again should now be successful:

----
busybox shell>  wget -S http://http-echo.ns-1.svc.cluster.local/test --post-data '{"message":"hello"}'
----

== Teardown

----
kubectl delete ns ns-1
----


== Advanced Topics

=== Preventing Outbound access

The Kubernetes Network Policies allow you to isolate inbound traffic only.  To filter outbound traffic, you need to configure Calico directly using the `calicoctl` tool.  Refer to the section https://docs.projectcalico.org/v2.6/getting-started/kubernetes/tutorials/advanced-policy[Prevent outgoing connections from pods] for further information.

