= Create Kubernetes cluster using Kops
:toc:

This tutorial will walk you through how to install a Kubernetes cluster using kops on AWS.

https://github.com/kubernetes/kops[Kops], short for Kubernetes Operations, is a set of tools for installing, operating, and deleting Kubernetes clusters in the cloud. A rolling upgrade of an older version of Kubernetes to a new version can also be performed. It also manages the cluster add-ons. After the cluster is created, the usual kubectl CLI can be used to manage resources in the cluster.

== Install kops

There is no need to download a Kubernetes binary distribution for creating a cluster using kops. However, you do need to download the kops CLI. It then takes care of downloading the right Kubernetes binary in the cloud, and provisions the cluster.

==== MacOS:
    brew update && brew install kops

==== Linux:
    wget https://github.com/kubernetes/kops/releases/download/1.7.1/kops-linux-amd64
    sudo chmod +x kops-linux-amd64
    sudo mv kops-linux-amd64 /usr/local/bin/kops

Kops is available on Mac OSX, Linux or the Windows 10 Linux Subsystem. Complete installation instructions are available at https://github.com/kubernetes/kops#installing.

For MacOS, if Kops is already installed, you can run the following command to upgrade to the latest the latest version:

    brew upgrade kops

Check kops version:

    $ kops version
    Version 1.7.1

Latest and early versions of kops can be downloaded from https://github.com/kubernetes/kops/releases.

In addition, you also need kubectl CLI to manage the resources on Kubernetes cluster. Instructions to install kubectl CLI are covered in link:../getting-started#setup-local-development-environment[].

=== Configuration kops

Kops uses a public SSH key while creating a cluster. The location of this file defaults to `~/.ssh/id_rsa.pub`. Please generate an SSH key if you don't have one. You can use the `--ssh-public-key` option to specify a custom location. More details about kops security can be found in the https://github.com/kubernetes/kops/blob/master/docs/security.md[kops docs].


== IAM user permission

Make sure the latest version of http://docs.aws.amazon.com/cli/latest/userguide/installing.html[AWS CLI]
is installed. User permissions used in this workshop must have these http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies.html[IAM policies] attached.

    AmazonEC2FullAccess
    AmazonRoute53FullAccess
    AmazonS3FullAccess
    IAMFullAccess
    AmazonVPCFullAccess

Please review these links for additional info on IAM permissions:
https://github.com/kubernetes/kops/blob/master/docs/aws.md#setup-iam-user. https://github.com/kubernetes/kops/blob/master/docs/iam_roles.md

== S3 bucket to store Kubernetes config

Kops needs a "`state store`" to store configuration information of the cluster.  For example, how many nodes in the cluster, the instance type of each node, and the Kubernetes version. The state is stored during the initial cluster creation. Any subsequent changes to the cluster are also persisted to this store. As of now, Amazon S3 is the only supported storage mechanism. Create an S3 bucket and pass that to the kops CLI during cluster creation.

NOTE: The bucket name must be unique otherwise you will encounter an error on deployment. For demonstration purposes only, we will use an example bucket name of `example-state-store`.

    # create variables for bucket, state store and cluster names
    export S3_BUCKET=example-state-store
    export KOPS_STATE_STORE=s3://${S3_BUCKET}

    # use aws cli to create bucket
    aws s3 mb $KOPS_STATE_STORE

    # enable versioning and export
    aws s3api put-bucket-versioning \
      --bucket $S3_BUCKET \
      --versioning-configuration \
      Status=Enabled

== Create cluster

The Kops CLI can be used to create a highly available cluster, with multiple master nodes spread across multiple Availability Zones. Workers can be spread across multiple zones as well. Some of the tasks that happen behind the scene during cluster creation are:

- Provisioning EC2 instances
- Setting up AWS resources such as networks, Auto Scaling groups, IAM users, and security groups
- Installing Kubernetes

When setting up a cluster you have two options on how the nodes in the cluster communicate:

. *Using DNS* - Creating a Kubernetes that uses DNS for node discovery requires a top-level domain or a subdomain and setting up Route 53 hosted zones. This allows the various Kubernetes components to find and communicate with each other. This is also needed for kubectl to be able to talk directly with the master.
. *Using the gossip protocol* - Kops has experimental support for a gossip-based cluster. This does not require a top-level domain, subdomain or a Route53 hosted zone to be registered. A gossip-based cluster is therefore easier and quicker to setup.

You'll need to choose one of the two options. Instructions for both options are provided below, and the examples in the workshop should work with either option. Creating a gossip-based cluster requires less setup and will be used in this workshop, unless otherwise specified.

=== Create a gossip-based Kubernetes cluster

Kops also has experimental support for a gossip-based cluster. It uses Weave Mesh behind the scenes. This makes the process of creating a Kubernetes cluster using kops DNS-free, and much simpler. This also means a top-level domain or a subdomain is no longer required to create the cluster. To create a cluster using the gossip protocol, indicate this to Kops by using a cluster name with a suffix of `.k8s.local`. In the following steps, we will use example.cluster.k8s.local as a sample gossip cluster name.

This is a fairly recent feature, so we recommend you continue to use DNS for production clusters. However, setting up a gossip-based cluster allows you to get started rather quickly.

We show two examples of creating gossip-based clusters below. You can choose whether to create a single-master or multi-master cluster. Workshop exercises will work on both types of cluster.

==== Default gossip-based cluster

By default, `create cluster` command creates a single master node and two worker nodes in the specified zones.

Create a Kubernetes cluster using the following command. This will create a cluster with a single master, multi-node and multi-az configuration:

    kops create cluster \
      --name example.cluster.k8s.local \
      --zones $AWS_AVAILABILITY_ZONES \
      --yes

The `create cluster` command only creates and stores the cluster config in the S3 bucket. Adding `--yes` option ensures that the cluster is immediately created as well.

Alternatively, you may not specify the `--yes` option as part of the `kops create cluster` command. Then you can use `kops edit cluster example.cluster.k8s.local` command to view the current cluster state and make changes. The cluster creation, in that case, is started with the following command:

    kops update cluster example.cluster.k8s.local --yes

Once the `kops create cluster` command is issued, it provisions the EC2 instances, setup Auto Scaling Groups, IAM users, security groups, and install Kubernetes on each node, configures master and worker nodes. This process can take a few minutes based upon the number of master and worker nodes.

Wait for 10-15 minutes and then the cluster can be validated as shown:

```
$ kops validate cluster
Using cluster from kubectl context: example.cluster.k8s.local

Validating cluster example.cluster.k8s.local

INSTANCE GROUPS
NAME      ROLE  MACHINETYPE MIN MAX SUBNETS
master-eu-central-1a Master  m3.medium 1 1 eu-central-1a
nodes     Node  t2.medium 2 2 eu-central-1a,eu-central-1b

NODE STATUS
NAME        ROLE  READY
ip-172-20-57-94.ec2.internal  master  True
ip-172-20-63-55.ec2.internal  node  True
ip-172-20-75-78.ec2.internal  node  True

Your cluster example.cluster.k8s.local is ready
```

validation of the cluster can fail if the node-counts aren't correct, it should infer sensible defaults (see #157). You can recreate the cluster and specify these counts.
```
    kops delete cluster --name example.cluster.k8s.local --yes
    kops create cluster \
      --name example.cluster.k8s.local \
      --zones $AWS_AVAILABILITY_ZONES \
      --node-count=3 \
      --master-count=1 \
      --yes 
```

==== Multi-master, multi-node, multi-az gossip-based cluster

Create a cluster with multi-master, multi-node and multi-az configuration. We can create and build the cluster in
one step by passing the `--yes` flag.

    kops create cluster \
      --name example.cluster.k8s.local \
      --master-count 3 \
      --master-zones $AWS_AVAILABILITY_ZONES \
      --node-count 5 \
      --zones $AWS_AVAILABILITY_ZONES \
      --yes

A multi-master cluster can be created by using the `--master-count` option and using an odd number value. The AZs for master can be specified using the `--master-zones` option. Kops will spread the servers across different AZs.

`--zones` is used to distribute the worker nodes. The number of workers is specified using the `--node-count` option.

As mentioned above, wait for 10-15 minutes for the cluster to be created. Validate the cluster:

```
$ kops validate cluster
Using cluster from kubectl context: example.cluster.k8s.local

Validating cluster example.cluster.k8s.local

INSTANCE GROUPS
NAME      ROLE  MACHINETYPE MIN MAX SUBNETS
master-eu-central-1a Master  m3.medium 1 1 eu-central-1a
master-eu-central-1b Master  m3.medium 1 1 eu-central-1b
master-eu-central-1c Master  c4.large  1 1 eu-central-1c
nodes     Node  t2.medium 5 5 eu-central-1a,eu-central-1b,eu-central-1c

NODE STATUS
NAME        ROLE  READY
ip-172-20-101-97.ec2.internal node  True
ip-172-20-119-53.ec2.internal node  True
ip-172-20-124-138.ec2.internal  master  True
ip-172-20-35-15.ec2.internal  master  True
ip-172-20-63-104.ec2.internal node  True
ip-172-20-69-241.ec2.internal node  True
ip-172-20-84-65.ec2.internal  node  True
ip-172-20-93-167.ec2.internal master  True

Your cluster example.cluster.k8s.local is ready
```

Note that all masters are spread across different AZs.

Your output may differ from the one shown here based up on the type of cluster you created.

=== Create a Kubernetes cluster in a private VPC

Kops can create a private Kubernetes cluster, where the master and worker nodes are launched in private subnets in a VPC. This is possible with both Gossip and DNS-based clusters. This reduces the attack surface on your instances by protecting them behind security groups inside private subnets. The services hosted in the cluster can still be exposed via internet-facing ELBs if required. It's necessary to run an overlay network in the Kubernetes cluster when using a private topology. We have used https://www.projectcalico.org/[Calico] below, though other options such as `kopeio-vxlan`, `weave` and `cni` are available.

Create a gossip-based private cluster with master and worker nodes in private subnets:

    kops create cluster \
      --networking calico \
      --topology private \
      --name example.cluster.k8s.local \
      --zones $AWS_AVAILABILITY_ZONES \
      --yes

Once the `kops create cluster` command is issued, it provisions the EC2 instances, setup Auto Scaling Groups, IAM users, security groups, and install Kubernetes on each node, configures master and worker nodes. This process can take a few minutes based upon the number of master and worker nodes.

Wait for 10-15 minutes and then the cluster can be validated as shown:

```
$ kops validate cluster
Using cluster from kubectl context: example.cluster.k8s.local

Validating cluster example.cluster.k8s.local

INSTANCE GROUPS
NAME                    ROLE    MACHINETYPE     MIN     MAX     SUBNETS
master-eu-central-1a    Master  m3.medium       1       1       eu-central-1a
nodes                   Node    t2.medium       2       2       eu-central-1a,eu-central-1b,eu-central-1c

NODE STATUS
NAME                                            ROLE    READY
ip-172-20-124-144.eu-central-1.compute.internal node    True
ip-172-20-58-179.eu-central-1.compute.internal  master  True
ip-172-20-93-220.eu-central-1.compute.internal  node    True

Your cluster example.cluster.k8s.local is ready
```

It is also possible to create a DNS-based cluster where the master and worker nodes are in private subnets. A `--dns-zone` argument is required to specify the domain. If `--dns private` is also specified, a Route53 private hosted zone is created for routing the traffic for the domain within one or more VPCs. The Kubernetes API can therefore only be accessed from within the VPC. This is a current issue with kops (see https://github.com/kubernetes/kops/issues/2032). A possible workaround is to mirror the private Route53 hosted zone with a public hosted zone that exposes only the API server ELB endpoint. This workaround is discussed http://kubecloud.io/setup-ha-k8s-kops/[here].

Although most of the exercises in this workshop should work on a cluster with a private VPC, some commands won't, specifically those that use a proxy to access internally hosted services.

=== Create a DNS-based Kubernetes cluster

To create a DNS-based Kubernetes cluster you'll need a top-level domain or subdomain that meets one of the following scenarios:

. Domain purchased/hosted via AWS
. A subdomain under a domain purchased/hosted via AWS
. Setting up Route53 for a domain purchased with another registrar, transfering the domain to Route53
. Subdomain for clusters in Route53, leaving the domain at another registrar

Then you need to follow the instructions in https://github.com/kubernetes/kops/blob/master/docs/aws.md#configure-dns[configure DNS]. Typically, the first and the last bullets are common scenarios.

==== Default DNS-based cluster

By default, `create cluster` command creates a single master node and two worker nodes in the specified zones.

Create a Kubernetes cluster using the following command. For the purposes of this demonstration, we will use a cluster name of example.cluster.com as our registered DNS. This will create a cluster with a single master, multi-node and multi-az configuration:

    kops create cluster \
      --name example.cluster.com \
      --zones $AWS_AVAILABILITY_ZONES \
      --yes

The `create cluster` command only creates and stores the cluster config in the S3 bucket. Adding `--yes` option ensures that the cluster is immediately created as well.

Alternatively, you may not specify the `--yes` option as part of the `kops create cluster` command. Then you can use `kops edit cluster example.cluster.com` command to view the current cluster state and make changes. The cluster creation, in that case, is started with the following command:

    kops update cluster example.cluster.com --yes

Once the `kops create cluster` command is issued, it provisions the EC2 instances, setup Auto Scaling Groups, IAM users, security groups, and install Kubernetes on each node, configures master and worker nodes. This process can take a few minutes based upon the number of master and worker nodes.

Wait for 10-15 minutes and then the cluster can be validated as shown:

```
$ kops validate cluster --name=example.cluster.com
Validating cluster example.cluster.com

INSTANCE GROUPS
NAME      ROLE  MACHINETYPE MIN MAX SUBNETS
master-eu-central-1a Master  m3.medium 1 1 eu-central-1a
nodes     Node  t2.medium 2 2 eu-central-1a,eu-central-1b

NODE STATUS
NAME        ROLE  READY
ip-172-20-51-232.ec2.internal node  True
ip-172-20-60-192.ec2.internal master  True
ip-172-20-91-39.ec2.internal  node  True

Your cluster example.cluster.com is ready
```

Verify the client and server version:

  $ kubectl version
  Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-12T00:45:05Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:30:51Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

It shows that Kubectl CLI version if 1.8.1 and the server version is 1.7.4.

==== Multi-master, multi-node, multi-az DNS-based cluster

Check the list of Availability Zones that exist for your region using the following command:

    aws --region <region> ec2 describe-availability-zones

Create a cluster with multi-master, multi-node and multi-az configuration. We can create and build the cluster in
one step by passing the `--yes` flag.

    kops create cluster \
      --name example.cluster.com \
      --master-count 3 \
      --master-zones $AWS_AVAILABILITY_ZONES \
      --node-count 5 \
      --zones $AWS_AVAILABILITY_ZONES \
      --yes

A multi-master cluster can be created by using the `--master-count` option and using an odd number value. The AZs for master can be specified using the `--master-zones` option. Kops will spread the nodes across different AZs.

`--zones` is used to distribute the worker nodes. The number of workers is specified using the `--node-count` option.

As mentioned above, wait for 10-15 minutes for the cluster to be created. Validate the cluster:

```
$ kops validate cluster --name=example.cluster.com
Validating cluster example.cluster.com

INSTANCE GROUPS
NAME      ROLE  MACHINETYPE MIN MAX SUBNETS
master-eu-central-1a Master  m3.medium 1 1 eu-central-1a
master-eu-central-1b Master  m3.medium 1 1 eu-central-1b
master-eu-central-1c Master  c4.large  1 1 eu-central-1c
nodes     Node  t2.medium 5 5 eu-central-1a,eu-central-1b,eu-central-1c

NODE STATUS
NAME        ROLE  READY
ip-172-20-103-30.ec2.internal master  True
ip-172-20-105-16.ec2.internal node  True
ip-172-20-127-147.ec2.internal  node  True
ip-172-20-35-38.ec2.internal  node  True
ip-172-20-47-199.ec2.internal node  True
ip-172-20-61-207.ec2.internal master  True
ip-172-20-75-78.ec2.internal  master  True
ip-172-20-94-216.ec2.internal node  True

Your cluster example.cluster.com is ready
```

Note that all masters are spread across different AZs.

Your output may differ from the one shown here based up on the type of cluster you created.

== Kubernetes cluster context

You may create multiple Kubernetes clusters. The configuration for each cluster is stored in a configuration file, referred to as "`kubeconfig file`". By default, kubectl looks for a file named `config` in the directory `~/.kube`. The kubectl CLI uses kubeconfig file to find the information it needs to choose a cluster and communicate with the API server of a cluster.

This allows you to deploy your applications to different environments by just changing the context. For example, here is a typical flow for application development:

. Build your application using minikube
. Change the context to a test cluster created on AWS
. Use the same command to deploy to test environment
. Once satisfied, change the context again to a production cluster on AWS
. Once again, use the same command to deploy to production environment

Get a summary of available contexts:

  $ kubectl config get-contexts
  CURRENT   NAME                CLUSTER             AUTHINFO            NAMESPACE
            cluster.k8s.local   cluster.k8s.local   cluster.k8s.local
  *         minikube            minikube            minikube

The output shows dfferent contexts, one per cluster, that are available to kubectl. `NAME` column shows the context name. `*` indicates the current context.

View the current context:

  $ kubectl config current-context
  cluster.k8s.local

If multiple clusters exist, then you can change the context:

  $ kubectl config use-context <config-name>

== Turn on an API version for your cluster

Kubernetes resources are created with a specific API version. The exact value is defined by the `apiVersion` attribute in the resource configuration file. Some of the values are `v1`, `extensions/v1beta1` or `batch/v1`. By default, resources with `apiVersion` values X, Y, Z are enabled. If a resource has a version with the word `alpha` in it, then that version needs to be explicitly enabled in the cluster. For example, if you are running a Kubernetes cluster of version 1.7.x, then Cron Job resource cannot be created unless `batch/v2alpha1` is explicitly enabled.

This section shows how to turn on an API version for your cluster. It will use `batch/v2alpha1` as an example.

Specific API versions can be turned on or off by passing `--runtime-config=api/<version>` flag while bringing up the API server. To turn on our specific version, we'll need to pass `--runtime-config=batch/v2alpha1=true`.

For a cluster created using kops, this can be done by editing the cluster configuration using the command shown:

  kops edit cluster --name example.cluster.k8s.local

This will open up the cluster configuration in a text editor. Update the `spec` attribute such that it looks like as shown:

    spec:
      kubeAPIServer:
        runtimeConfig:
          batch/v2alpha1: "true"
      api:

Save the changes and exit the editor. Kubernetes cluster needs to re-read the configuration. This can be done by forcing a rolling update of the cluster using the following command:

NOTE: This process can easily take 30-45 minutes. Its recommended to leave the cluster without any updates during that time.

  $ kops rolling-update cluster --force --yes
  Using cluster from kubectl context: example.cluster.k8s.local

  NAME                    STATUS  NEEDUPDATE      READY   MIN     MAX     NODES
  master-eu-central-1a    Ready   0               1       1       1       1
  nodes                   Ready   0               2       2       2       2
  I1025 20:50:51.158013     354 instancegroups.go:350] Stopping instance "i-0ba714556f0f892cc", node "ip-172-20-58-179.eu-central-1.compute.internal", in AWS ASG "master-eu-central-1a.masters.example.cluster.k8s.local".
  I1025 20:55:51.413506     354 instancegroups.go:350] Stopping instance "i-0265a07c3320b266b", node "ip-172-20-93-220.eu-central-1.compute.internal", in AWS ASG "nodes.example.cluster.k8s.local".
  I1025 20:57:52.448582     354 instancegroups.go:350] Stopping instance "i-09e2efd9f5e9ebfce", node "ip-172-20-124-144.eu-central-1.compute.internal", in AWS ASG "nodes.example.cluster.k8s.local".
  I1025 20:59:53.325980     354 rollingupdate.go:174] Rolling update completed!

This command will first stop one master node in the cluster, re-read the configuration information and start that master. Then it will do the same for rest of the master nodes. And then it will repeat that for each worker node in the cluster. After all the server and worker nodes have been restarted, the rolling update of the cluster is complete.

Let's verify that the attributes are now successfully passed to the API server. Get the list of pods for the API server using the command shown:

  $ kubectl get pods --all-namespaces | grep kube-apiserver
  kube-system   kube-apiserver-ip-172-20-117-32.ec2.internal            1/1       Running   0          7m
  kube-system   kube-apiserver-ip-172-20-62-108.ec2.internal            1/1       Running   6          16m
  kube-system   kube-apiserver-ip-172-20-79-64.ec2.internal             1/1       Running   2          12m

The output shows three pods, one each for API server, corresponding to the three master nodes. This output is from a cluster with three master nodes. The output may be different if your cluster was created with different number of masters. 

Search for the `--runtime-config` option as shown:

  $ kubectl describe --namespace=kube-system pod <pod-name> | grep runtime

`<pod-name>` is name of one of the pods shown above.

A formatted output is shown below:

  /usr/local/bin/kube-apiserver \
    --address=127.0.0.1 \
    --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,ResourceQuota \
    --allow-privileged=true \
    --anonymous-auth=false \
    --apiserver-count=3 \
    --authorization-mode=AlwaysAllow \
    --basic-auth-file=/srv/kubernetes/basic_auth.csv \
    --client-ca-file=/srv/kubernetes/ca.crt \
    --cloud-provider=aws \
    --etcd-servers-overrides=/events#http://127.0.0.1:4002 \
    --etcd-servers=http://127.0.0.1:4001 --insecure-port=8080 --kubelet-preferred-address-types=InternalIP,Hostname,ExternalIP \
    --runtime-config=batch/v2alpha1=true \
    --secure-port=443 \
    --service-cluster-ip-range=100.64.0.0/13 \
    --storage-backend=etcd2 \
    --tls-cert-file=/srv/kubernetes/server.cert \
    --tls-private-key-file=/srv/kubernetes/server.key \
    --token-auth-file=/srv/kubernetes/known_tokens.csv \
    --v=2 \
    1>>/var/log/kube-apiserver.log 2>&1

The output clearly shows that `--runtime-config=batch/v2alpha1=true` is passed as an option to the API server. This means the cluster is now ready for creating creating APIs with version `batch/v2alpha1`.

== Delete cluster

Any cluster can be deleted as shown:

    kops delete cluster \
      <cluster-name> \
      --yes

`<cluster-name>` is the name of the cluster. For example, our `example.cluster.k8s.local` cluster can be deleted as:

    kops delete cluster \
      example.cluster.k8s.local \
      --yes

If you created a private VPC, then an additional cleanup of resources is required as shown below:

    # Find Route53 hosted zone ID from the console or via CLI and delete hosted zone
    aws route53 delete-hosted-zone --id Z1234567890ABC
    # Delete VPC if you created earlier
    aws ec2 detach-internet-gateway --internet $IGW --vpc $VPCID
    aws ec2 delete-internet-gateway --internet-gateway-id $IGW
    aws ec2 delete-vpc --vpc-id $VPCID
