= Kubernetes Workshop Prereqs
:toc:

Here are the pre-requisites for the link:readme.adoc[Kubernetes on AWS workshop]:

== AWS Account

You will be using an AWS Account while you go through the workshop. link:http://docs.aws.amazon.com/AmazonSimpleDB/latest/DeveloperGuide/AboutAWSAccounts.html[Create an AWS Account] if you don't already have one.

Please ensure you followed all sign up steps. If you don't do this, then you likely run into the following error while completing the step to set the AWS Availability Zones:
```
An error occurred (OptInRequired) when calling the DescribeAvailabilityZones operation: You are not subscribed to this service. Please go to http://aws.amazon.com to subscribe
```
NOTE: You will incur charges as you go through these workshop guides as it will exceed the link:http://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/free-tier-limits.html[limits of AWS free tier]. An estimate of charges (<$20/day) can be seen at this link:https://calculator.s3.amazonaws.com/index.html#r=FRA&s=EC2&key=calc-E6DBD6F1-C45D-4827-93F8-D9B18C5994B0[simple monthly calculator].

== AWS CLI

Install the latest version of http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-bundle.html[AWS CLI] on your machine.

=== Setup on macOS

Provision and install AWS CLI on a Mac OS via https://brew.sh/[homebrew].

. Install homebrew and cask

    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

. Install AWS CLI

    brew install awscli

=== Setup on Windows

The Windows 10 Linux subsystem is required if you are using Windows 10.

Install Windows 10 Linux subsystem as explained at https://msdn.microsoft.com/en-us/commandline/wsl/install_guide.

The lab has been tested with Windows 10. A similar Unix shell on other Windows machines may work.

. http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-windows.html

=== Setup on Linux

. http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-linux.html

== AWS IAM Permissions

If you already have an AWS Account, you need to create an IAM user to use during the workshop.
If you have not created an IAM admin user and group yet, please do so in the following section.
If you already have admin user then skip to <<Create IAM user for workshop, Create IAM user for workshop>>

=== Create admin user and group (optional)
Please go to https://console.aws.amazon.com/iam/home#/users and click on `Add user`. As a username choose `Administrator`, select the `Programmatic access` checkbox and hit `Next: Permissions`.

In the next dialog select `Create group`, choose `Administrators`, select the `AdministratorAccess` policy and click `Create group`.

Finally click `Next: Review` and `Create user` in the final dialog.

Now you see your newly admin user and group together with the `Access key ID`. To see the `Secret access key` once, click on `Show` next to the stars.

To login from the console run `aws configure` and enter the required values. It will look like this:

```
aws configure
AWS Access Key ID [None]: *****
AWS Secret Access Key [None]: *****
Default region name [None]: eu-central-1
Default output format [None]:
```

=== Create IAM user for workshop

Run the following commands on CLI to create the needed group and user:

```
aws iam create-group --group-name k8s-workshop

aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonEC2FullAccess --group-name k8s-workshop
aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonRoute53FullAccess --group-name k8s-workshop
aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess --group-name k8s-workshop
aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/IAMFullAccess --group-name k8s-workshop
aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonVPCFullAccess --group-name k8s-workshop

aws iam create-user --user-name k8s-workshop

aws iam add-user-to-group --user-name k8s-workshop --group-name k8s-workshop

aws iam create-access-key --user-name k8s-workshop
```

Now run `aws configure` again and use the `Access Key ID` and `Secret Access Key` from the newly created user.

Please review this link:https://github.com/kubernetes/kops/blob/master/docs/aws.md#setup-iam-user[link]
for additional info on IAM permissions

== AWS Availability Zones

Different availability zones for this region can be set in the environment variable `AWS_AVAILABILITY_ZONES` using the following command:

    export AWS_AVAILABILITY_ZONES="$(aws ec2 describe-availability-zones --query 'AvailabilityZones[].ZoneName' --output text | awk -v OFS="," '$1=$1')"

Echo the value of the environment variable to confirm:

    echo $AWS_AVAILABILITY_ZONES
    eu-central-1a,eu-central-1b,eu-central-1c

Several parts of the workshop require the region or availability zones to be explicitly specified as a CLI option. The region is picked based upon the value set in `aws configure` command. The environment variable `$AWS_AVAILABILITY_ZONES` is used to set the availability zones.

== Clone the repo

The workshop repo has configuration files that are used to create Kubernetes resources. You need to clone the repo to have access to those files:

	$ git clone https://github.com/arun-gupta/kubernetes-aws-workshop/

== Need Help

Please https://github.com/arun-gupta/kubernetes-aws-workshop/issues[file a bug] if you run into issues.
