= Kubernetes Workshop Prereqs
:toc:

Here are the pre-requisites for the link:readme.adoc[Kubernetes on AWS workshop]:

== Windows 10 Linux Subsystem

This pre-requisite is only if you are using Windows 10.

Install Windows 10 Linux subsystem as explained at https://msdn.microsoft.com/en-us/commandline/wsl/install_guide.

The lab has been tested with Windows 10. A similar Unix shell on other Windows machines may work.

== AWS Account

You will be using an AWS Account while you go through the workshop. link:http://docs.aws.amazon.com/AmazonSimpleDB/latest/DeveloperGuide/AboutAWSAccounts.html[Create an AWS Account] if you don't already have one.

== AWS CLI

Install the latest version of http://docs.aws.amazon.com/cli/latest/userguide/awscli-install-bundle.html[AWS CLI] on your machine.

== AWS IAM Permissions

If you already have an AWS Account, you need to create an IAM user to use during the workshop. Make sure you have run `aws configure` with your personal `Access Key ID`, `Secret Access Key`, and your default region (see link:http://docs.aws.amazon.com/general/latest/gr/rande.html[this page] for a list of available regions). 

Run the following commands on CLI to create the needed group and user:

```
aws iam create-group --group-name k8s-workshop

aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonEC2FullAccess --group-name k8s-workshop
aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonRoute53FullAccess --group-name k8s-workshop
aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess --group-name k8s-workshop
aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/IAMFullAccess --group-name k8s-workshop
aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonVPCFullAccess --group-name k8s-workshop

aws iam create-user --user-name k8s-workshop

aws iam add-user-to-group --user-name k8s-workshop --group-name k8s-workshop

aws iam create-access-key --user-name k8s-workshop
```

Now run `aws configure` again and use the `Access Key ID` and `Secret Access Key` from the newly created user.

Please review this link:https://github.com/kubernetes/kops/blob/master/docs/aws.md#setup-iam-user[link]
for additional info on IAM permissions

== AWS Availability Zones

Different availability zones for this region can be set in the environment variable `AWS_AVAILABILITY_ZONES` using the following command:

    AWS_AVAILABILITY_ZONES="$(aws ec2 describe-availability-zones --query 'AvailabilityZones[].ZoneName' --output text | awk -v OFS="," '$1=$1')"

Echo the value of the environment variable to confirm:

    echo $AWS_AVAILABILITY_ZONES
    eu-central-1a,eu-central-1b,eu-central-1c

Several parts of the workshop require the region or availability zones to be explicitly specified as a CLI option. The region is picked based upon the value set in `aws configure` command. The environment variable `$AWS_AVAILABILITY_ZONES` is used to set the availability zones.

== Clone the repo

The workshop repo has configuration files that are used to create Kubernetes resources. You need to clone the repo to have access to those files:

	$ git clone https://github.com/arun-gupta/kubernetes-aws-workshop/

== Need Help

Please https://github.com/arun-gupta/kubernetes-aws-workshop/issues[file a bug] if you run into issues.
