= Kubernetes Workshop Prereqs
:toc:

Here are the pre-requisites for the link:readme.adoc[Kubernetes on AWS workshop]:

== AWS Account

You will be using an AWS Account while you go through the workshop. link:http://docs.aws.amazon.com/AmazonSimpleDB/latest/DeveloperGuide/AboutAWSAccounts.html[Create an AWS Account] if you don't already have one

== IAM Permissions

If you already have an AWS Account, you need to create an IAM user and attach these http://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies.html[IAM policies].

    AmazonEC2FullAccess
    AmazonRoute53FullAccess
    AmazonS3FullAccess
    IAMFullAccess
    AmazonVPCFullAccess

Please review this link:https://github.com/kubernetes/kops/blob/master/docs/aws.md#setup-iam-user[link]
for additional info on IAM permissions

== AWS CLI

Install the latest version of http://docs.aws.amazon.com/cli/latest/userguide/installing.html[AWS CLI]
on your machine.

== AWS Region and Availability Zones

Use `eu-central-1` AWS region for this workshop. Default AWS region used by the AWS CLI can be set using this command:

    export AWS_DEFAULT_REGION=eu-central-1

Different availability zones for this region can be set in the environment variable `AWS_AVAILABILITY_ZONES` using the following command:

    AWS_AVAILABILITY_ZONES=`aws --region $AWS_DEFAULT_REGION ec2 describe-availability-zones --query AvailabilityZones[].ZoneName --output text | awk -v OFS="," '$1=$1'`

Echo the value of the environment variable to confirm:

    echo $AWS_AVAILABILITY_ZONES
    eu-central-1a,eu-central-1b,eu-central-1c

Several parts of the workshop require the region or availability zones to be explicitly specified as a CLI option. The environment variable `$AWS_DEFAULT_REGION` is used to set the region. The environment variable `$AWS_AVAILABILITY_ZONES` is used to set the availability zones.

== Clone the repo

The workshop repo has configuration files that are used to create Kubernetes resources. You need to clone the repo to have access to those files:

	$ git clone https://github.com/arun-gupta/kubernetes-aws-workshop/

== Need Help

Please https://github.com/arun-gupta/kubernetes-aws-workshop/issues[file a bug] if you run into issues.
