= Kubernetes on AWS Workshop

This is a self-paced workshop that explains how to run and manage a Kubernetes cluster on Amazon Web Services. It also explains how to deploy, scale and configure applications on this cluster.

This workshop is targeted for attendees in both Developer and Operations teams who would like to get started with Kubernetes on Amazon Web Services (AWS).

It will provide instructions to create, manage and scale a Kubernetes cluster on AWS. Deep integration with several AWS technologies will be shown.

It will also explain how to deploy applications, scale them, run stateless and stateful containers, perform service discovery between different microservices and other similar concepts.

The proposed agenda is to go through the described format to ramp up your knowledge on Kubernetes by following
the workshop guides. You are also encouraged to take a detour and learn advanced topics if you feel comfortable
as you move through the workshop.

[cols="1*"]
|===
|Beginners

|link:prereqs.adoc[Pre-requisites]
|link:getting-started[Setup Development Environment and First Steps]
|link:cluster-install[Create Kubernetes cluster using Kops]
|link:developer-concepts[Kubernetes Developer Concepts]
|===

[cols="1*"]
|===
|Mid-level (200 - 300)

| link:config-secrets[Configuration and Secrets Management]
| link:microservices[Service discovery with microservices]
| link:helm[Deploy applications using Helm charts]
| link:cluster-logging[Logging with Kubernetes cluster]
| link:cluster-monitoring[Monitoring with Kubernetes cluster]
| link:upgrade-clusters#inplace-upgrade[Upgrading Kubernetes cluster - inplace upgrade]
| Upgrading Kubernetes cluster - blue/green upgrade
| link:cluster-scaling[Cluster scaling]
| link:app-scaling[Pod Autoscaling]
|===

[cols="1*"]
|===
|Advanced (300+)

| link:statefulsets[StatefulSets with EBS]
| link:calico[Network policies with Calico]
| link:roles[Managing IAM roles with kube2iam]
| CI/CD pipeline
| ALB ingress controller
| Nginx ingress controller
| link:service-mesh[Service mesh integration using Linkerd and Istio]
|===

