= Kubernetes on AWS Workshop

This is a self-paced workshop that explains how to run and manage a Kubernetes cluster on Amazon Web Services. 
It explains how to deploy, scale, and configure applications on this cluster.

This workshop is designed for attendees on Development and Operations teams who would like to get started with Kubernetes on Amazon Web Services (AWS).

This workshop provides instructions to create, manage, and scale a Kubernetes cluster on AWS, as well as how to deploy applications, scale them, run stateless and stateful containers, perform service discovery between different microservices, and other similar concepts.

It also shows deep integration with several AWS technologies.

The proposed agenda is to go through the described format to ramp up your knowledge on Kubernetes by following
the workshop guides. 
You are also encouraged to take a detour and explore advanced topics if you feel comfortable
as you move through the workshop.

[cols="1*"]
|===
|Beginner (100 level)

|link:prereqs.adoc[Prerequisites]
|link:getting-started[Setup Development Environment and First Steps]
|link:cluster-install[Create a Kubernetes cluster using kops]
|link:developer-concepts[Kubernetes Developer Concepts]
|===

[cols="1*"]
|===
|Intermediate (200 - 300 level)

| link:config-secrets[Configuration and Secrets Management]
| link:microservices[Service Discovery with Microservices]
| link:helm[Deploy Applications using Helm Charts]
| link:app-update[Updating Applications & Canary Deployment]
| link:cluster-logging[Logging within a Kubernetes cluster]
| link:cluster-monitoring[Monitoring within a Kubernetes cluster]
| link:cluster-upgrade#inplace-upgrade[Upgrading a Kubernetes cluster: In-place Upgrade]
| Upgrading a Kubernetes cluster: Blue/Green Upgrade
| link:cluster-scaling[Cluster Ccaling]
| link:app-scaling[Application Autoscaling]
|===

[cols="1*"]
|===
|Advanced (300 - 400+ level)

| link:statefulsets[StatefulSets with EBS]
| link:calico[Network policies with Calico]
| link:coredns[Using CoreDNS for Service Discovery]
| link:roles[Managing IAM roles with kube2iam]
| CI/CD pipeline
| ALB ingress controller
| Nginx ingress controller
| link:service-mesh[Service mesh integration using Linkerd and Istio]
|===

