= Kubernetes on AWS Workshop

This is a self-paced workshop that explains how to run and manage a Kubernetes cluster on Amazon Web Services. It also explains how to deploy, scale and configure applications on this cluster.

This workshop is targeted for attendees in both Developer and Operations team, and who would like to get started with Kubernetes on Amazon Web Services (AWS).

It will provide instructions on create, manage, scale a Kubernetes cluster on AWS. A deep integration with several AWS technologies will be shown.

It will also explain how to deploy applications, scale them, running stateless and stateful containers, service discovery between different microservices and other similar concepts.

Proposed agenda is to go through the described format to rampup your knowledge on Kubernetes by following
the workshop guides. You are also encouraged to take a detour and learn advanced topics if you feel comfortable
as you move through the workshop.

[cols="1*"]
|===
|Beginners

|link:prereqs.adoc[Pre-requisites]
|link:getting-started[Kubernetes Getting started]
|link:cluster-install[Install Kubernetes cluster using kops]
|link:deployment-concepts[Kubernetes Deployment concepts]
|===

[cols="1*"]
|===
|Mid-level (200 - 300)

| link:microservices[Service discovery with microservices]
| link:helm[Deploy applications using Helm charts]
| link:cluster-logging[Logging with Kubernetes cluster]
| link:cluster-monitoring[Monitoring with Kubernetes cluster]
| link:upgrade-clusters#inplace-upgrade[Upgrading Kubernetes cluster - inplace upgrade]
| Upgrading Kubernetes cluster - blue/green upgrade
| link:cluster-scaling[Cluster scaling]
| link:config-secretsConfiguration and Secrets Management
| link:app-scaling[Pod Autoscaling]
|===

[cols="1*"]
|===
|Advanced (300+)

| link:calico[Network policies with Calico]
| link:roles[Managing IAM roles with kube2iam]
| CI/CD pipeline
| link:statefulsets[StatefulSets with EBS]
| ALB ingress controller
| Nginx ingress controller
| link:service-mesh#linkerd[Service mesh integration using Linkerd]
| Service mesh integration using Istio
|===

