:toc:
= Kubernetes Getting Started
:icons:
:linkcss:
:imagesdir: ../images


== Deploy a "Production Ready Cluster" (part 3 of 4)

This tutorial will be broken up into two different options:

* Gossip based cluster for test/dev - use this if you do not have access to a publically routable domain and zone file
* Single Region, Multi AZ Master and Nodes - this is a production ready cluster

== Install pre-requisites

Will not cover these items but you need to have the AWS CLI tool installed along with kubectl which we installed in a previous tutorial.

The AWS CLI should be configured with a user that has the following IAM permissions:

    AmazonEC2FullAccess
    AmazonRoute53FullAccess
    AmazonS3FullAccess
    IAMFullAccess
    AmazonVPCFullAccess

Install KOPS:

    brew update and brew install --HEAD kops

== Gossip based cluster for test/dev

This option is for users that do not have access to a publically routable domain, a gossip based cluster is suitable for us in test/dev environments

== Single Region, Multi Master/Node

== Additional options

== Conclusion

In this second part of our series we explored some of the basic Kubernetes CLI commands, deployed our first pod and queried the Kubernetes API to gain additional insight into the resources we deployed.

== Next steps



./setupKopsCluster.adoc[Deploy a Production Ready Cluster]
