:icons:
:linkcss:
:imagesdir: ../images

= Kubernetes ConfigMap and Secrets
:toc:

Kubernetes has resource types that allows to decouple application code from configuration. It makes the applications to be more portable.

ConfigMap is just a set of key-value pairs. It allow you to decouple configuration artifacts from image content. Secrets allows separating sensitive information such as credentials and keys from an application. ConfigMap is similar to Secrets, but provides a means of working with strings that don’t contain sensitive information.

This section will explain how to use ConfigMap and Secrets.

== ConfigMap

We will illiustrate how to pass this information to a Redis pod, by passing configuration information with Configmap.

=== Create the ConfigMap object

    kubectl apply -f ./templates/config-map.yaml

=== Deploy a Redis pod

Deploy a Redis pod that maps the Configmap to the volume where the configuration resides:

    kubectl apply -f ./templates/redis-pod.yaml

=== Validate Redis cluster

Validate that your redis cluster picked up the appropriate configuration:

    kubectl exec --it redis redis-cli
    CONFIG GET maxmemory
    CONFIG GET maxmemory-policy

You should see the same values that were specified in the ./templates/config-map.yaml outputted in the above commands.

== Secrets

In this section we will demonstrate how to place secrets into the Kubernetes cluster and then show multiple ways of retrieving those secretes from within pods.

=== Create secrets

First encode the secrets you want to apply, for this example we will use the username `admin` and the password `password`

    echo -n "admin" | base64
    echo -n "password" | base64

Both of these values are already written in the file `./templates/secret.yaml`

You can now insert this secret in to kubernetes with the following command:

    kubectl apply -f ./templates/secret.yaml

=== Consume secrets

Here we will demonstrate two ways to consume secrets from within pods.

==== Using volumes

Deploy the pod:

    kubectl apply -f ./templates/pod-secret-volume.yaml

Open a shell to the pod to see the secrets

    kubectl exec -it pod-secret-volume /bin/bash
    ls /etc/foo
    cat /etc/foo/username ; echo
    cat /etc/foo/password ; echo

The above commands should result in the plain text values, the decoding is done for you.

==== Using Environment Variables

Deploy the pod:

    kubectl apply -f ./templates/pod-secret-env.yaml

Open a shell to the pod to see the secrets:

    kubectl exec -it pod-secret-volume /bin/bash
    echo $SECRET_USERNAME
    echo $SECRET_PASSWORD

The above commands illustrate how to see the secret values via environment variables

