= Defining a Network Policy
:toc:
:imagesdir: ../images


== What is Network Policy?

Kubernetes provides an API that allows you to specify which pods can communicate with other pods. Policy is defined and described in YAML files and then passed to a “network policy controller” by Kubernetes.

Network policies are implemented by an add-on; there are several available.  Any of these solutions allow you to specify a network policy and then enforce the rules while your services are running.

== Calico

Calico is an open-source plugin that allows for fine-grained network policy enforcement, ensuring that traffic within your Kubernetes cluster can only flow in the direction that you specify. As an example, if we take a scenario where Kubernetes namespaces are used to enforce boundaries between products, or even enforce boundaries between different environments (e.g. development vs production), network policies can be configured to ensure no unauthorized network traffic is allowed beyond its boundary. Think of it as being similar to applying Security Groups in the AWS world.


