= Defining a Network Policy
:toc:
:imagesdir: ../images


== What is Network Policy?

Kubernetes Network Policy objects allow for fine-grained network policy enforcement, ensuring that traffic within your Kubernetes cluster can only flow in the direction that you specify.  As an example, if we take a scenario where Kubernetes namespaces are used to enforce boundaries between products, or even enforce boundaries between different environments (e.g. development vs production), network policies can be configured to ensure no unauthorized network traffic is allowed beyond its boundary.  Think of it as being similar to applying Security Groups in the AWS world.

Network policies are implemented by an add-on; there are several available.  Any of these solutions allow you to specify a network policy and then enforce the rules while your services are running.

== Calico

https://www.projectcalico.org[Calico] is an open-source plugin that implements pod networking and Network Policy.

| link:calico[Define Network Policy with Calico]


== Weave Net

https://www.weave.works/docs/net/latest/kubernetes/kube-addon/[Weave Net] is an open-source plugin that implements pod networking and Network Policy.

If you're using https://www.weave.works/docs/cloud/latest/concepts/network-policy/[Weave Cloud] you can visualize your container networks and services all from a single dashboard and also configure monitoring to alert you about any suspicious network activity.

| link:weave-net[Define Network Policy with Weave Net]
