= Using CoreDNS for Service Discovery

:toc:

This tutorial will show you how to update an existing Kubernetes cluster to use https://coredns.io/[coredns] instead of the default https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/dns[kube-dns] for service discovery.

== Pre-requisites

A 3 master nodes and 5 worker nodes cluster as explained at link:../cluster-install##multi-master-multi-node-multi-az-gossip-based-cluster[] is used for this chapter.

All configuration files for this chapter are in the `cluster-logging` directory.

== Status Quo

In every fresh Kubernetes cluster we will find a service named kube-dns that forwards all dns requests to a pod responsible for handling dns requests.

This is what it looks like in a fresh `minikube`:

```
kubectl describe svc kube-dns -n kube-system
Name:			kube-dns
Namespace:		kube-system
Labels:			addonmanager.kubernetes.io/mode=Reconcile
			k8s-app=kube-dns
			kubernetes.io/name=KubeDNS
Annotations:		kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kube-dns","kubernet...
Selector:		k8s-app=kube-dns
Type:			ClusterIP
IP:			10.0.0.10
Port:			dns	53/UDP
Endpoints:		172.17.0.7:53
Port:			dns-tcp	53/TCP
Endpoints:		172.17.0.7:53
Session Affinity:	None
Events:			<none>
```

To validate that the current dns setup is working we first have to deploy a `busybox` pod: `kubectl create -f busybox.yaml`.

Lets resolve the `kubernetes` service in the `default` namespace:
```
kubectl exec -ti busybox -- nslookup kubernetes.default
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default
Address 1: 10.0.0.1 kubernetes.default.svc.cluster.local
```
From here we can see, that the `kube-dns` service answered our request and the `kubernetes` service can be found at `10.0.0.1` - this looks perfect!

As a last step lets look at the `resolv.conf`:
```
kubectl exec busybox cat /etc/resolv.conf
nameserver 10.0.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```
As expected, we see that the nameserver IP corresponds to the IP of the `kube-dns` service. Additionally the search domains also reflect the expected kubernetes schema (get more  link:https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/[here])

Now that we validated the current setup, lets deploy coredns.

== Deploying coredns

The `coredns` deployment relies on information which is specific to you cluster: CIDR of kubernetes services and cluster domain.
For minikube, you can deploy `coredns` from a pre-generated yaml: `kubectl create -f coredns-minikube.yaml`

Wait until the `coredns` pod is running:
```
kubectl get po -l k8s-app=coredns -n kube-system
NAME                       READY     STATUS    RESTARTS   AGE
coredns-3986650266-gw79f   1/1       Running   0          17s
```

== Switching to coredns

The only thing left is updating the `kube-dns` service to use our coredns pod: `kubectl apply -f coredns-service.yaml`

When you describe the `kube-dns` service now, it should look something like this:
```
kubectl describe svc kube-dns -n kube-system
Name:			kube-dns
Namespace:		kube-system
Labels:			k8s-app=coredns
			kubernetes.io/cluster-service=true
			kubernetes.io/name=CoreDNS
Annotations:		kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"coredns","kubernetes.io/cluster-service":"true","kubernetes.io/na...
Selector:		k8s-app=coredns
Type:			ClusterIP
IP:			10.0.0.10
Port:			dns	53/UDP
Endpoints:		172.17.0.10:53
Port:			dns-tcp	53/TCP
Endpoints:		172.17.0.10:53
Port:			metrics	9153/TCP
Endpoints:		172.17.0.10:9153
Session Affinity:	None
Events:			<none>
```

If all went correct, the IP of our coredns pod should match the endpoint IPs in the `kube-dns` service:
```
kubectl get po -l k8s-app=coredns -n kube-system -o wide
NAME                       READY     STATUS    RESTARTS   AGE       IP            NODE
coredns-3986650266-gw79f   1/1       Running   0          20m       172.17.0.10   minikube
```

Awesome, this fits nicely!

To be completely sure, you can re-execute the commands from the <<Status Quo>> section which validate the setup.

== Delete kube-dns deployment (optional)

As a very last step we can delete the original `kube-dns` deployment: `kubectl delete deployment kube-dns -n kube-system`

This will delete the pod and only our coredns implementation will still be available.

