= Daemon Sets

== Creating a DaemonSet
The folowing will be an example DaemonSet that runs a logstash image. Let's begin with the template:

	apiVersion: extensions/v1beta1
	kind: DaemonSet
	metadata:
	  name: logstash-daemonset
	  labels:
	    app: logstash
	spec:
	  template:
	    metadata:
	      labels:
	        app: logstash
	    spec:
	      containers:
	      - name: logstash
	        image: logstash:5.5.2
	        imagePullPolicy: IfNotPresent # if exists, will not pull new image
	        resources:
	          limits:
	            memory: 50Mi
	          requests:
	            cpu: 50m
	            memory: 50Mi
	        volumeMounts:
	        - name: varlog
	          mountPath: /var/log
	        - name: varlibdockercontainers
	          mountPath: /var/lib/docker/containers
	          readOnly: true
	      volumes:
	      - name: varlog
	        hostPath:
	          path: /var/log
	      - name: varlibdockercontainers
	        hostPath:
	          path: /var/lib/docker/containers

Run the following command to create the ReplicaSet and pods:

	kubectl create -f https://github.com/arun-gupta/kubernetes-aws-workshop/blob/master/templates/daemonset.yaml --record

The *--record* flag will track changes made through each revision.

To track the ReplicaSet details type in the following:

	kubectl describe ds/logstash-daemonset

The output should look similar the following:

	$ kubectl describe ds
	Name:           logstash-daemonset
	Selector:       app=logstash
	Node-Selector:  <none>
	Labels:         app=logstash
	Annotations:    kubernetes.io/change-cause=kubectl create --filename=daemonset.yaml --record=true
	Desired Number of Nodes Scheduled: 3
	Current Number of Nodes Scheduled: 3
	Number of Nodes Scheduled with Up-to-date Pods: 3
	Number of Nodes Scheduled with Available Pods: 3
	Number of Nodes Misscheduled: 0
	Pods Status:    3 Running / 0 Waiting / 0 Succeeded / 0 Failed
	Pod Template:
	  Labels:       app=logstash
	  Containers:
	   logstash:
	    Image:      logstash:5.5.2
	    Port:       <none>
	    Limits:
	      memory:   50Mi
	    Requests:
	      cpu:              50m
	      memory:           50Mi
	    Environment:        <none>
	    Mounts:
	      /var/lib/docker/containers from varlibdockercontainers (ro)
	      /var/log from varlog (rw)
	  Volumes:
	   varlog:
	    Type:       HostPath (bare host directory volume)
	    Path:       /var/log
	   varlibdockercontainers:
	    Type:       HostPath (bare host directory volume)
	    Path:       /var/lib/docker/containers
	Events:
	  FirstSeen     LastSeen        Count   From            SubObjectPath   Type            Reason                  Message
	  ---------     --------        -----   ----            -------------   --------        ------                  -------
	  6s            6s              1       daemon-set                      Normal          SuccessfulCreate        Created pod: logstash-daemonset-zjw24
	  6s            6s              1       daemon-set                      Normal          SuccessfulCreate        Created pod: logstash-daemonset-b0w72
	  6s            6s              1       daemon-set                      Normal          SuccessfulCreate        Created pod: logstash-daemonset-hb365

== Limiting DaemonSets to Specific Nodes
Verify that the logstash pod was successfully deployed to the cluster nodes:

	kubectl get pods -o wide

Output should mirror the following:

	$ kubectl get pods -o wide
	NAME                       READY     STATUS    RESTARTS   AGE       IP           NODE
	logstash-daemonset-b0w72   1/1       Running   1          1m        100.96.2.9   ip-172-20-76-225.us-west-2.compute.internal
	logstash-daemonset-hb365   1/1       Running   0          1m        100.96.1.9   ip-172-20-38-189.us-west-2.compute.internal
	logstash-daemonset-zjw24   1/1       Running   2          1m        100.96.3.9   ip-172-20-121-97.us-west-2.compute.internal

Rename one of the node labels as follows:

	kubectl label node ip-172-20-38-189.us-west-2.compute.internal app=logstash-node

Next, edit the DaemonSet template to include a nodeSelector that matches the changed label:

	................
	spec:
	  nodeSelector:
	    app: logstash-node
      containers:
      - name: logstash
        image: logstash:5.5.2
    ................

After the update is performed, we have now configured logstash to run off a specific node:

	$ kubectl get pods
	NAME                       READY     STATUS        RESTARTS   AGE
	logstash-daemonset-hb365   1/1       Running       5          26m
	logstash-daemonset-pzvkw   1/1       Terminating   0          1m
	logstash-daemonset-t9f0n   1/1       Terminating   0          1m