:toc:

= Kubernetes Concepts
Kubernetes contains a number of abstractions that map to API objects. These Kubernetes API Objects can be used to describe your cluster's desired state which will include info such as applications and workloads running, replicas, container images, networking resources and more. Below are a few examples.

== Deployments
A desired state can be described in a Deployment object. The Deployment controller changes the actaul state to the desired state. 
https://github.com/arun-gupta/kubernetes-aws-workshop/blob/master/deployment-concepts/deployments.adoc

== Replica Sets
A RepllicaSet specifies a number of pod repliacas that can be run at any given time. The Deployment manages the ReplicaSets and provides updates to those pods. ReplicaSets can be used in lieu of Deployments if you require custom orchestration or do not need updates.
https://github.com/arun-gupta/kubernetes-aws-workshop/blob/master/deployment-concepts/replicasets.adoc

== Daemon Sets
DeamonSets allow the cluster of nodes to run a specified pod. As nodes are added, pods are added. As nodes are removed, pods are removed through garbage collection.  
https://github.com/arun-gupta/kubernetes-aws-workshop/blob/master/deployment-concepts/daemonsets.adoc

== Services
A Kubernetes service defines a logical set of pods and enables them to be access through micro-services. 
https://github.com/arun-gupta/kubernetes-aws-workshop/blob/master/deployment-concepts/services.adoc