:toc:

= Kubernetes Developer Concepts

Kubernetes has a number of abstractions that map to API objects. These Kubernetes API Objects can be used to describe your cluster's desired state which will include info such as applications and workloads running, replicas, container images, networking resources and more. This section explains the key concepts relevant from an application developer perspecitve.

== Pre-requisites

A 3 master nodes and 5 worker nodes cluster as explained at link:../cluster-install#multi-master-multi-worker-cluster-highly-available[] is used for this chapter.

== Deployments

A "`desired state`", such as 4 replicas of a pod, can be described in a Deployment object. The Deployment controller in Kubernetes cluster then ensures the desired and the actual state are matching. Deployment ensures the recreation of a pod when the worker node fails or reboots. It also allows both up- and down-scaling the number of replicas. 

If a pod dies, then a new pod is started to ensure the desired vs actual matches.

=== Create a Deployment

The folowing example will create a Deployment with 3 replicas of NGINX base image. Let's begin with the template:

	apiVersion: extensions/v1beta1
	kind: Deployment # kubernetes object type
	metadata:
	  name: nginx-deployment # deployment name
	spec:
	  replicas: 3 # number of replicas
	  template:
	    metadata:
	      labels:
	        app: nginx # pod labels
	    spec:
	      containers:
	      - name: nginx # container name
	        image: nginx:1.12.1 # nginx image
	        imagePullPolicy: IfNotPresent # if exists, will not pull new image
	        ports: # container and host port assignments
	        - containerPort: 80
	        - containerPort: 443

This deployment will create 3 instances of NGINX image.

Run the following command to create Deployment:

	$ kubectl create -f templates/deployment.yaml --record
	deployment "nginx-deployment" created

The `--record` flag will track changes made through each revision.

To monitor deployment rollout status:

	$ kubectl rollout status deployment/nginx-deployment
	deployment "nginx-deployment" successfully rolled out

A Deployment creates a ReplicaSet to manage the number of replicas. Let's take a look at existing deployments and replica set.

Get the deployments:

	$ kubectl get deployments
	NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
	nginx-deployment   3         3         3            3           25s

Get the replica set for the deployment:

	$ kubectl get replicaset
	NAME                          DESIRED   CURRENT   READY     AGE
	nginx-deployment-3441592026   3         3         3         1m

Get the list of running pods:

	$ kubectl get pods
	NAME                                READY     STATUS    RESTARTS   AGE
	nginx-deployment-3441592026-ddpf0   1/1       Running   0          2m
	nginx-deployment-3441592026-kkp8h   1/1       Running   0          2m
	nginx-deployment-3441592026-lx304   1/1       Running   0          2m

=== Scaling a Deployment

Number of replicas for a Deployment can be scaled using the following command:

	$ kubectl scale --replicas=5 deployment/nginx-deployment
	deployment "nginx-deployment" scaled

Verify the deployment:

	$ kubectl get deployments
	NAME               DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
	nginx-deployment   5         5         5            5           2m

Verify the pods in the deployment:

	$ kubectl get pods
	NAME                                READY     STATUS    RESTARTS   AGE
	nginx-deployment-3441592026-36957   1/1       Running   0          44s
	nginx-deployment-3441592026-8wch5   1/1       Running   0          44s
	nginx-deployment-3441592026-ddpf0   1/1       Running   0          3m
	nginx-deployment-3441592026-kkp8h   1/1       Running   0          3m
	nginx-deployment-3441592026-lx304   1/1       Running   0          3m

=== Update a Deployment

A more general update to Deployment can be made by making edits to the pod spec. In this example, let's change to the latest nginx image.

First, type the following to open up a text editor:

	kubectl edit deployment/nginx-deployment

Next, change the image from `nginx:1.12.1` to `nginx:latest`.

This should perform a rolling update of the deployment. To track the deployment details such as revision, image version, and ports - type in the following:

```
$ kubectl describe deployments
Name:                   nginx-deployment
Namespace:              default
CreationTimestamp:      Mon, 23 Oct 2017 09:14:36 -0400
Labels:                 app=nginx
Annotations:            deployment.kubernetes.io/revision=2
                        kubernetes.io/change-cause=kubectl edit deployment/nginx-deployment
Selector:               app=nginx
Replicas:               5 desired | 5 updated | 5 total | 5 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:  app=nginx
  Containers:
   nginx:
    Image:        nginx:latest
    Ports:        80/TCP, 443/TCP
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   nginx-deployment-886641336 (5/5 replicas created)
Events:
  Type    Reason             Age                From                   Message
  ----    ------             ----               ----                   -------
  Normal  ScalingReplicaSet  4m                 deployment-controller  Scaled up replica set nginx-deployment-3441592026 to 3
  Normal  ScalingReplicaSet  1m                 deployment-controller  Scaled up replica set nginx-deployment-3441592026 to 5
  Normal  ScalingReplicaSet  32s                deployment-controller  Scaled up replica set nginx-deployment-886641336 to 1
  Normal  ScalingReplicaSet  32s                deployment-controller  Scaled down replica set nginx-deployment-3441592026 to 4
  Normal  ScalingReplicaSet  32s                deployment-controller  Scaled up replica set nginx-deployment-886641336 to 2
  Normal  ScalingReplicaSet  29s                deployment-controller  Scaled down replica set nginx-deployment-3441592026 to 3
  Normal  ScalingReplicaSet  29s                deployment-controller  Scaled up replica set nginx-deployment-886641336 to 3
  Normal  ScalingReplicaSet  28s                deployment-controller  Scaled down replica set nginx-deployment-3441592026 to 2
  Normal  ScalingReplicaSet  28s                deployment-controller  Scaled up replica set nginx-deployment-886641336 to 4
  Normal  ScalingReplicaSet  25s (x3 over 26s)  deployment-controller  (combined from similar events): Scaled down replica set nginx-deployment-3441592026 to 0
```

=== Rollback a Deployment

To rollback to a previous version, first check the revision history:

	$ kubectl rollout history deployment/nginx-deployment
	deployments "nginx-deployment"
	REVISION  CHANGE-CAUSE
	1         kubectl scale deployment/nginx-deployment --replicas=5
	2         kubectl edit deployment/nginx-deployment

If you only want to rollback to the previous revision, enter the following command:

	$ kubectl rollout undo deployment/nginx-deployment
	deployment "nginx-deployment" rolled back

In our case, the deployment will rollback to use the `nginx:1.12.1` image. Check the image name:

	$ kubectl describe deployments | grep Image
    Image:        nginx:1.12.1

If rolling back to a specific revision then enter:

	kubectl rollout undo deployment/nginx-deployment --to-revision=<version>

=== Delete a Deployment

Run the following command to delete deployment:

	$ kubectl delete -f templates/deployment.yaml
	deployment "nginx-deployment" deleted

== Replica Sets

A RepllicaSet specifies a number of pod replicas that can be run at any given time. The Deployment manages the ReplicaSets and provides updates to those pods. ReplicaSets can be used in lieu of Deployments if you require custom orchestration or do not need updates.

For replica set, matching of pods is done according to a set of values. The supported operators are `in`, `notin` and `exists` (only for the key). For example, replication controller can select pods such as "`environment = dev`". Replica set can select pods such as "`environment in ["dev", "test"]`".

=== Create a ReplicaSet

The folowing will be an example ReplicaSet with an NGINX base image. Let's begin with the template:

	apiVersion: extensions/v1beta1
	kind: ReplicaSet
	metadata:
	  name: nginx-replicaset
	spec:
	  replicas: 3
	  template:
	    metadata:
	      labels:
	        name: nginx-replica
	    spec:
	      containers:
	      - name: nginx-replica
	        image: nginx:1.12.1
	        imagePullPolicy: IfNotPresent
	        ports:
	        - containerPort: 80
	        - containerPort: 443

Run the following command to create the ReplicaSet and pods:

	$ kubectl create -f templates/replicaset.yaml --record
	replicaset "nginx-replicaset" created

The `--record` flag will track changes made through each revision.

Get the list of replica sets:

	$ kubectl get rs
	NAME               DESIRED   CURRENT   READY     AGE
	nginx-replicaset   3         3         3         40s

To track the replica set details type in the following:

```
$ kubectl get rs
NAME               DESIRED   CURRENT   READY     AGE
nginx-replicaset   3         3         3         40s
developer-concepts $ kubectl describe rs/nginx-replicaset
Name:         nginx-replicaset
Namespace:    default
Selector:     name=nginx-replica
Labels:       name=nginx-replica
Annotations:  kubernetes.io/change-cause=kubectl create --filename=templates/replicaset.yaml --record=true
Replicas:     3 current / 3 desired
Pods Status:  3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  name=nginx-replica
  Containers:
   nginx-replica:
    Image:        nginx:1.12.1
    Ports:        80/TCP, 443/TCP
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age   From                   Message
  ----    ------            ----  ----                   -------
  Normal  SuccessfulCreate  1m    replicaset-controller  Created pod: nginx-replicaset-p46sn
  Normal  SuccessfulCreate  1m    replicaset-controller  Created pod: nginx-replicaset-dhzfn
  Normal  SuccessfulCreate  1m    replicaset-controller  Created pod: nginx-replicaset-18290
```

=== Scale a Replica Set

Number of replicas in a Replica Set can be scaled up using the following command:

	$ kubectl scale --replicas=5 rs/nginx-replicaset
	replicaset "nginx-replicaset" scaled

Get the list of replica set:

	$ kubectl get rs
	NAME               DESIRED   CURRENT   READY     AGE
	nginx-replicaset   5         5         5         2m

Get the list of pods:

	$ kubectl get pods
	NAME                     READY     STATUS    RESTARTS   AGE
	nginx-replicaset-18290   1/1       Running   0          8m
	nginx-replicaset-dhzfn   1/1       Running   0          8m
	nginx-replicaset-p46sn   1/1       Running   0          8m
	nginx-replicaset-qwttl   1/1       Running   0          5m
	nginx-replicaset-xgvwx   1/1       Running   0          5m

=== Delete a Replica Set

A Replica Set can be deleted using the following command:

	$ kubectl delete rs/nginx-replicaset
	replicaset "nginx-replicaset" deleted

== Services

A pod is ephemeral. Each pod is assigned a unique IP address. If a pod that belongs to a replication controller dies, then it is recreated and may be given a different IP address. Further, aAdditional pods may be created using Deployment or Replica Set. This makes it difficult for an application server, such as WildFly, to access a database, such as MySQL, using its IP address.

A Service is an abstraction that defines a logical set of pods and a policy by which to access them. The IP address assigned to a service does not change over time, and thus can be relied upon by other pods. Typically, the pods belonging to a service are defined by a label selector. This is similar mechanism to how pods belong to a replica set.

This abstraction of selecting pods using labels enables a loose coupling. The number of pods in the deployment may scale up or down but the application server can continue to access the database using the service.

A Kubernetes service defines a logical set of pods and enables them to be access through micro-services.

=== Create a Deployment for Service

Pods belong to a service by using a loosely-coupled model where labels are attached to a pod and a service picks the pods by using those labels.

Let's create a Deployment first that will create 3 replicas of a pod:

	apiVersion: extensions/v1beta1
	kind: Deployment
	metadata:
	  name: echo-deployment 
	spec:
	  replicas: 3 
	  template:
	    metadata:
	      labels:
	        app: echo-pod
	    spec:
	      containers:
	      - name: echoheaders 
	        image: gcr.io/google_containers/echoserver:1.4
	        imagePullPolicy: IfNotPresent 
	        ports: 
	        - containerPort: 8080


This example creates an echo app that responds with HTTP headers from an Elastic Load Balancer.

Type the following to create the deployment:

	kubectl create -f templates/echo-deployment.yaml --record

Use the `kubectl describe deployment` command to confirm `echo-app` has been deployed:

```
$ kubectl describe deployment
Name:                   echo-deployment
Namespace:              default
CreationTimestamp:      Mon, 23 Oct 2017 10:07:47 -0400
Labels:                 app=echo-pod
Annotations:            deployment.kubernetes.io/revision=1
                        kubernetes.io/change-cause=kubectl create --filename=templates/echo-deployment.yaml --record=true
Selector:               app=echo-pod
Replicas:               3 desired | 3 updated | 3 total | 3 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:  app=echo-pod
  Containers:
   echoheaders:
    Image:        gcr.io/google_containers/echoserver:1.4
    Port:         8080/TCP
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   echo-deployment-3396249933 (3/3 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  10s   deployment-controller  Scaled up replica set echo-deployment-3396249933 to 3
```

Get the list of pods:

```
$ kubectl get pods
NAME                               READY     STATUS    RESTARTS   AGE
echo-deployment-3396249933-8slzp   1/1       Running   0          1m
echo-deployment-3396249933-bjwqj   1/1       Running   0          1m
echo-deployment-3396249933-r05nr   1/1       Running   0          1m
```

Check the label for a pod:

```
kubectl describe pods/echo-deployment-3396249933-8slzp | grep Label
Labels:         app=echo-pod
```

Each pod in this deployment has `app=echo-pod` label attached to it.

=== Create a Service

In the following example, we create a service `echo-service`:

	apiVersion: v1
	kind: Service
	metadata:
	  name: echo-service
	spec:
	  selector:
	    app: echo-pod
	  ports:
	  - name: http
	    protocol: TCP
	    port: 80
	    targetPort: 8080
	  type: LoadBalancer

The set of pods targeted by the service are determined by the label `app: echo-pod` attached to them. It also defines an inbound port 80 to the target port of 8080 on the container.

Kubernetes supports both TCP and UDP protocols.

=== Publish a Service

A service can be published to an external IP using the `type` attribute. This attribute can take one of the following values:

. `ClusterIP`: Service exposed on an IP address inside the cluster. This is the default behavior.
. `NodePort`: Service exposed on each Node's IP address at a defined port.
. `LoadBalancer`: If deployed in the cloud, exposed externally using a cloud-specific load balancer. 
. `ExternalName`: Service is attached to the `externalName` field. It is mapped to a CNAME with the value.

Let's publish the service load balancer and expose your services, add a `type` field of `LoadBalancer`.

This template will expose `echo-app` service on an Elastic Load Balancer (ELB):

	apiVersion: v1
	kind: Service
	metadata:
	  name: echo-service
	spec:
	  selector:
	    app: echo-pod
	  ports:
	  - name: http
	    protocol: TCP
	    port: 80
	    targetPort: 8080
	  type: LoadBalancer

Run the following command to create the service:

	kubectl create -f templates/service.yaml --record

Get more details about the service:

```
$ kubectl get svc
NAME           TYPE           CLUSTER-IP       EXTERNAL-IP        PORT(S)        AGE
echo-service   LoadBalancer   100.66.161.199   ad0b47976b7fe...   80:30125/TCP   40s
kubernetes     ClusterIP      100.64.0.1       <none>             443/TCP        1h
developer-concepts $ kubectl describe service echo-service
Name:                     echo-service
Namespace:                default
Labels:                   <none>
Annotations:              kubernetes.io/change-cause=kubectl create --filename=templates/service.yaml --record=true
Selector:                 app=echo-pod
Type:                     LoadBalancer
IP:                       100.66.161.199
LoadBalancer Ingress:     ad0b47976b7fe11e7a8870e55a29a6a9-1770422890.us-east-1.elb.amazonaws.com
Port:                     http  80/TCP
TargetPort:               8080/TCP
NodePort:                 http  30125/TCP
Endpoints:                100.96.3.8:8080,100.96.4.9:8080,100.96.5.9:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  CreatingLoadBalancer  58s   service-controller  Creating load balancer
  Normal  CreatedLoadBalancer   56s   service-controller  Created load balancer
```

Access the service using the LoadBalancer Ingress:

```
curl http://ad0b47976b7fe11e7a8870e55a29a6a9-1770422890.us-east-1.elb.amazonaws.com
CLIENT VALUES:
client_address=172.20.45.253
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://ad0b47976b7fe11e7a8870e55a29a6a9-1770422890.us-east-1.elb.amazonaws.com:8080/

SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001

HEADERS RECEIVED:
accept=*/*
host=ad0b47976b7fe11e7a8870e55a29a6a9-1770422890.us-east-1.elb.amazonaws.com
user-agent=curl/7.51.0
BODY:
-no body in request-
```

Note the `client_address` value shown in the output. This is the IP address of the pod serving the request. Multiple invocations of this command will show different values for this attribute.

Now, the number of pods in the deployment can be scaled up and down. Or the pods may terminate and restart on a different host. But the service will still be able to target those pods because of the labels attached to the pod and used by the service.

=== Delete a Service

Delete the service:

    kubectl delete -f templates/service.yaml

The backend deployment needs to be explicitly deleted as well:

    kubectl delete -f templates/echo-deployment.yaml

== Daemon Sets

DeamonSets allow the cluster of nodes to run a specified pod. As nodes are added, pods are added. As nodes are removed, pods are removed through garbage collection.  

=== Create a DaemonSet

The folowing will be an example DaemonSet that runs a logstash image. Let's begin with the template:

	apiVersion: extensions/v1beta1
	kind: DaemonSet
	metadata:
	  name: logstash-daemonset
	  labels:
	    app: logstash
	spec:
	  template:
	    metadata:
	      labels:
	        app: logstash
	    spec:
	      containers:
	      - name: logstash
	        image: logstash:5.5.2
	        imagePullPolicy: IfNotPresent # if exists, will not pull new image
	        resources:
	          limits:
	            memory: 50Mi
	          requests:
	            cpu: 50m
	            memory: 50Mi
	        volumeMounts:
	        - name: varlog
	          mountPath: /var/log
	        - name: varlibdockercontainers
	          mountPath: /var/lib/docker/containers
	          readOnly: true
	      volumes:
	      - name: varlog
	        hostPath:
	          path: /var/log
	      - name: varlibdockercontainers
	        hostPath:
	          path: /var/lib/docker/containers

Run the following command to create the ReplicaSet and pods:

	kubectl create -f templates/daemonset.yaml --record

The `--record` flag will track changes made through each revision.

To track the ReplicaSet details type in the following:

	kubectl describe ds/logstash-daemonset

The output should look similar the following:

	$ kubectl describe ds
	Name:           logstash-daemonset
	Selector:       app=logstash
	Node-Selector:  <none>
	Labels:         app=logstash
	Annotations:    kubernetes.io/change-cause=kubectl create --filename=daemonset.yaml --record=true
	Desired Number of Nodes Scheduled: 3
	Current Number of Nodes Scheduled: 3
	Number of Nodes Scheduled with Up-to-date Pods: 3
	Number of Nodes Scheduled with Available Pods: 3
	Number of Nodes Misscheduled: 0
	Pods Status:    3 Running / 0 Waiting / 0 Succeeded / 0 Failed
	Pod Template:
	  Labels:       app=logstash
	  Containers:
	   logstash:
	    Image:      logstash:5.5.2
	    Port:       <none>
	    Limits:
	      memory:   50Mi
	    Requests:
	      cpu:              50m
	      memory:           50Mi
	    Environment:        <none>
	    Mounts:
	      /var/lib/docker/containers from varlibdockercontainers (ro)
	      /var/log from varlog (rw)
	  Volumes:
	   varlog:
	    Type:       HostPath (bare host directory volume)
	    Path:       /var/log
	   varlibdockercontainers:
	    Type:       HostPath (bare host directory volume)
	    Path:       /var/lib/docker/containers
	Events:
	  FirstSeen     LastSeen        Count   From            SubObjectPath   Type            Reason                  Message
	  ---------     --------        -----   ----            -------------   --------        ------                  -------
	  6s            6s              1       daemon-set                      Normal          SuccessfulCreate        Created pod: logstash-daemonset-zjw24
	  6s            6s              1       daemon-set                      Normal          SuccessfulCreate        Created pod: logstash-daemonset-b0w72
	  6s            6s              1       daemon-set                      Normal          SuccessfulCreate        Created pod: logstash-daemonset-hb365

=== Limit DaemonSets to specific nodes

Verify that the logstash pod was successfully deployed to the cluster nodes:

	kubectl get pods -o wide

Output should mirror the following:

	$ kubectl get pods -o wide
	NAME                       READY     STATUS    RESTARTS   AGE       IP           NODE
	logstash-daemonset-b0w72   1/1       Running   1          1m        100.96.2.9   ip-172-20-76-225.us-west-2.compute.internal
	logstash-daemonset-hb365   1/1       Running   0          1m        100.96.1.9   ip-172-20-38-189.us-west-2.compute.internal
	logstash-daemonset-zjw24   1/1       Running   2          1m        100.96.3.9   ip-172-20-121-97.us-west-2.compute.internal

Rename one of the node labels as follows:

	kubectl label node ip-172-20-38-189.us-west-2.compute.internal app=logstash-node

Next, edit the DaemonSet template to include a nodeSelector that matches the changed label:

	................
	spec:
	  nodeSelector:
	    app: logstash-node
      containers:
      - name: logstash
        image: logstash:5.5.2
    ................

After the update is performed, we have now configured logstash to run off a specific node:

	$ kubectl get pods
	NAME                       READY     STATUS        RESTARTS   AGE
	logstash-daemonset-hb365   1/1       Running       5          26m
	logstash-daemonset-pzvkw   1/1       Terminating   0          1m
	logstash-daemonset-t9f0n   1/1       Terminating   0          1m

=== Delete a DaemonSet

