
= Kubernetes - App Scaling
:icons:
:linkcss:
:imagesdir: ../images

== Kubernetes - App Scaling

Horizontal Pod Autoscaling (HPA) is a Kubernetes feature to dynamically increase/decrease the number of pod replicas based on resource utilization metrics.

Heapster is an open source project that collects cluster metrics, and Kubernetes integrates with it to determine CPU consumption. Heapster's default backend, referred to as a "sink", is InfluxDB. Additional sinks are supported including Elasticsearch.

Kubernetes currently has beta support for custom metrics from multiple sources, and not just Heapster. This is enabled via the API Server Aggregation feature, and this documentation will be updated when the feature is live to show HPA with additional types of metrics.

HPA can automatically scale pods deployed in a replication controller, deployment, or a replica set. For additional information on how HPA works, check out the Kubernetes https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/[community documentation].

=== Prerequisistes

1. https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/install-cluster[Deploy a Kubernetes cluster] and verify that it works
2. Deploy Heapster using the steps described in the https://github.com/arun-gupta/kubernetes-aws-workshop/tree/master/cluster-monitoring[Cluster Monitoring] lab.

=== Deploy an Application

In this step, we deploy a simple Go web application and constrain the CPU resources just for the purposes of this test.

    $ kubectl run webapp --image=trevorrobertsjr/webapp --requests=cpu=50m --expose --port=8080

=== Horizontal Pod Autoscaler Configuration

Now that our application is running, we create a Horizonal Pod Autoscaler for our webapp deployment.

    $ kubectl autoscale deployment webapp --cpu-percent=10 --min=1 --max=10

=== Generate Load

The simplest method to do this would be to access the application in an infinite loop similar to the example in the Kubernetes Horizonal Pod Autoscaler documentation:

First, deploy a busybox container, label it *load-generator* and attach to it's prompt:

    $ kubectl run -i --tty load-generator --image=busybox /bin/sh

At the command prompt, run a continuous request of the webapp

    $ while true; do wget -q -O- http://webapp.default.svc.cluster.local; done

If for any reason you get disconnected from the load-generator container, you can re-attach to it with the following command.

    $ kubectl attach $(kubectl get pod | grep load | awk '{print $1}') -c load-generator -i -t

In a different terminal window, check the status of the Horizontal Pod Autoscaler.

    $ kubectl get hpa

You will see output similar to the following over successive executions of the *kubectl get hpa* command:

    $ kubectl get hpa
    NAME         REFERENCE               TARGETS      MINPODS   MAXPODS   REPLICAS   AGE
    webapp       Deployment/webapp       0% / 10%   1         10        1          2m

    $ kubectl get hpa
    NAME         REFERENCE               TARGETS      MINPODS   MAXPODS   REPLICAS   AGE
    webapp       Deployment/webapp       206% / 10%   1         10        1          3m

    $ kubectl get hpa
    NAME         REFERENCE               TARGETS      MINPODS   MAXPODS   REPLICAS   AGE
    webapp       Deployment/webapp       222% / 10%   1         10        4          4m

Notice that, eventually, the value in the *REPLICAS* column will increase the longer the load generator is allowed to run.

In the terminal window that is running the load generator, hit Ctrl-C. Again, run the *kubectl get hpa* command every few minutes, and you will see the number of replicas begin to decrease as the CPU load returns to 0%

== Conclusion

In this post we demonstrated how to dynamically scale application due to average CPU utilization by the application. Heapster is the resource monitoring tool that Kubnertes integrates with to enable HPA, and Heapster can be used with a variety of backends (or "sinks"), including Elasticsearch, to store its data.
