= Setup Cluster with Route53 Private Hosted Zone
:icons:
:linkcss:
:imagesdir: ../images

=== Install kops and kubectl on your PC
    $ brew install kops
    $ curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl
    $ chmod +x ./kubectl
    $ sudo mv ./kubectl /usr/local/bin/kubectl

=== create bucket to store k8s config info
    $ aws s3api create-bucket --bucket dalbhanj-kubernetes-aws-io
    # enable versioning and export
    $ aws s3api put-bucket-versioning --bucket dalbhanj-kubernetes-aws-io --versioning-configuration Status=Enabled
    $ export KOPS_STATE_STORE=s3://dalbhanj-kubernetes-aws-io

=== create private hosted zone on R53
    $ ID=$(uuidgen) && aws route53 create-hosted-zone --name kubernetes-aws.io --vpc VPCRegion=us-west-2,VPCId=vpc-9dc7cdff --caller-reference $ID

== create k8s cluster by re-using existing VPC
    $ kops create cluster --dns private --name mycluster.kubernetes-aws.io --zones us-west-2a,us-west-2b --state s3://dalbhanj-kubernetes-aws-io --vpc vpc-9dc7cdff --network-cidr 10.1.0.0/16 --ssh-public-key $mypubkey
    # view new cluster
    $ kops get cluster
    # After creating a basic cluster spec, you can edit subnet ID to ensure VPC config is correct
    $ kops edit cluster mycluster.kubernetes-aws.io
    # kops doc suggests to remove cidr ip block (bcoz it will be queried when you save config) and to add subnet ID subnets:
    - cidr: 172.20.32.0/19 # You can delete the CIDR here; it will be queried
      name: us-west-2a
      type: Public
      zone: us-west-2a
      id: subnet-1234567 # Replace this with the ID of your subnet
    - cidr: 172.20.32.0/19 # You can delete the CIDR here; it will be queried
      name: us-west-2b
      type: Public
      zone: us-west-2b
      id: subnet-1234567 # Replace this with the ID of your subnet
    # review changes and confirm
    $ kops update cluster mycluster.kubernetes-aws.io
    $ kops update cluster mycluster.kubernetes-aws.io --yes
    # validate cluster failed due to DNS issues

=== Small Hack
    # if you don't own domain name but still want to use DNS based communication using Route53 private hosted zone rather than gossip protocol (not sure how mature gossip protocol is for advanced topics such as federation etc)
    # login to master node and run kops and other commands from there
    # make sure your Route53 records reflect correct IP addresses and your zone is associated with correct VPCs
    # make sure your VPC has both DNS resolution and DNS hostnames set to "yes"
    ##
    ## install kops on master node
    ##
    $ ssh -i $mykey admin@api.mycluster.kubernetes-aws.io
    $ wget https://github.com/kubernetes/kops/releases/download/1.6.1/kops-linux-amd64
    $ chmod +x kops-linux-amd64
    $ mv kops-linux-amd64 /usr/local/bin/kops
    $ export KOPS_STATE_STORE=s3://dalbhanj-kubernetes-aws-io
    $ export NAME=mycluster.kubernetes-aws.io
    ##
    ## change the API endpoint to internal dns in kube configuration
    $ vi ~/.kube/config
    server: https://api.internal.mycluster.kubernetes-aws.io
    ## validate cluster
    $ kops validate cluster mycluster.kubernetes-aws.io
    $ kubectl get nodes
    ## copy kube configuration (~/.kube/config) to master node if you still encounter error (CAUTION: Need to investigate what the implications will be on the cluster if you do this)

== create standalone cluster using gossip protocol (dns-free)
    $ kops create cluster my3rdcluster.k8s.local --zones us-west-2a,us-west-2b --state s3://dalbhanj-kubernetes-aws-io --yes
    $ kops validate cluster
    $ kubectl get nodes

== create k8s cluster with a new VPC
    $ kops create cluster --dns private --name my2ndcluster.kubernetes-aws.io --zones us-west-2a,us-west-2b --state s3://dalbhanj-kubernetes-aws-io --ssh-public-key $mypubkey
    # update cluster to add another AZ us-west-2c
    $ kops edit cluster my2ndcluster.kubernetes-aws.io
      - cidr: 172.20.96.0/19
        name: us-west-2c
        type: Public
        zone: us-west-2c
    ## Go to small hack portion to run rest of administrative commands from the master node
